services:
  expo-app:
    build: .
    container_name: cityfix
    dns:
      - 8.8.8.8
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    tty: true
    command: tail -f /dev/null